# Generated by Django 5.0.6 on 2024-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                auto_created=True,
                blank="True",
                null="True",
                verbose_name="дата создания",
            ),
        ),
    ]
