# Generated by Django 5.0.6 on 2024-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(max_length=150, verbose_name="URL"),
        ),
    ]
