# Generated by Django 4.2.2 on 2024-07-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blog_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "verbose_name": "Личный кабинет",
                "verbose_name_plural": "Личные кабинеты",
            },
        ),
    ]
