# Generated by Django 4.2.2 on 2024-07-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер версии"),
                ),
                (
                    "name",
                    models.CharField(
                        default="V_1", max_length=100, verbose_name="Название версии"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Актуальная"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="blog.blog",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия товара",
                "verbose_name_plural": "Версии товара",
            },
        ),
    ]
