# Generated by Django 5.0.6 on 2024-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Введите описание",
                null=True,
                unique=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Загрузите изображение",
                null=True,
                upload_to="product/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
