# Generated by Django 5.0.6 on 2024-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_description_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
