# Generated by Django 5.0.6 on 2024-06-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Введите номер версии",
                        max_length=50,
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите наименование версии",
                        max_length=255,
                        verbose_name="Наименование версии",
                    ),
                ),
                (
                    "is_current_version",
                    models.BooleanField(default=False, verbose_name="Аквтивная версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Выберите продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия товара",
                "verbose_name_plural": "Версии товара",
            },
        ),
    ]
