# Generated by Django 5.0.6 on 2024-06-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_version_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите номер версии",
                unique=True,
                verbose_name="Номер версии",
            ),
        ),
    ]
