# Generated by Django 5.0.6 on 2024-06-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_version_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="is_current_version",
        ),
        migrations.RemoveField(
            model_name="version",
            name="version_name",
        ),
        migrations.RemoveField(
            model_name="version",
            name="version_number",
        ),
        migrations.AddField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="Актуальная"),
        ),
        migrations.AddField(
            model_name="version",
            name="name",
            field=models.CharField(
                default="V_1", max_length=100, verbose_name="Название версии"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="number",
            field=models.PositiveIntegerField(default=1, verbose_name="Номер версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
    ]
