# Generated by Django 4.2.2 on 2024-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату выпуска",
                null=True,
                verbose_name="Дата выпуска",
            ),
        ),
    ]
