# Generated by Django 4.2.2 on 2024-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, null=True, verbose_name="URL"
            ),
        ),
    ]
